[build]
  publish = "public"
  command = "hugo --baseURL=https://recipez.netlify.com/"

[context.production.environment]
  HUGO_VERSION = "0.36"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.36"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.36"

[context.master]
  command = "hugo -D --baseURL=https://master--recipez.netlify.com/"

[context.uat]
  command = "hugo --baseURL=https://uat--recipez.netlify.com/"
